# Generated by Django 2.2 on 2019-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=48)),
                ('lang', models.CharField(default='en_US', max_length=10)),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='TaskManager_email_afd4cd_idx'),
        ),
    ]
