# Generated by Django 2.2 on 2019-05-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=4096)),
                ('issue_type', models.IntegerField()),
                ('created', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('resolved', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=48)),
                ('lang', models.CharField(default='en_US', max_length=10)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TaskManager.UserProfile')),
                ('token', models.CharField(max_length=32)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='TaskManager_email_afd4cd_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.UserProfile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to='TaskManager.UserProfile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to='TaskManager.UserProfile'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.Project'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token'], name='TaskManager_token_59836c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='TaskManager_owner_i_6e25b5_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['creator'], name='TaskManager_creator_fa65bf_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee'], name='TaskManager_assigne_9658f1_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['name'], name='TaskManager_name_1cd6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='TaskManager_status_3aaed7_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created'], name='TaskManager_created_ba4513_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['issue_type'], name='TaskManager_issue_t_240a5e_idx'),
        ),
    ]
