# Generated by Django 2.2 on 2019-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
