# Generated by Django 2.2 on 2019-04-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20190412_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.UserProfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='TaskManager_owner_i_6e25b5_idx'),
        ),
    ]
