# Generated by Django 2.2 on 2019-04-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20190429_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.UserProfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['user', 'token'], name='TaskManager_user_id_81abd3_idx'),
        ),
    ]
