# Generated by Django 2.2 on 2019-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_auto_20190429_1213'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='token',
            name='TaskManager_user_id_81abd3_idx',
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token'], name='TaskManager_token_59836c_idx'),
        ),
    ]
